[package]
name = "cranelift-spectre"
version = "0.1.0"
authors = ["shravanrn@gmail.com <shravanrn@gmail.com>"]
edition = "2018"

[dependencies]
num-traits = ">=0.2"
num-derive = ">=0.2"
libc = ">=0.2.70"
sysconf = ">=0.3.4"